# Setup
title:        UKChannel8
tagline:      Great TV. By women, for women. Register your interest.
baseurl:      ""
paginate:     1

# About/contact
author:
  name:       Kelly-Anne Smith
  url:        http://UKChannel8.com 

# Gems
gems:
  - jekyll-paginate

#Others
markdown: kramdown
