# Setup
title:        UKChannel<strong style="color:black;">8</strong>
tagline:      Great TV.<br>By women, for women.<br><br><i><small>Register your interest.</small></i>
baseurl:      ""
paginate:     1

# About/contact
author:
  name:       Kelly-Anne Smith
  url:        http://UKChannel8.com 

# Gems
gems:
  - jekyll-paginate

#Others
markdown: kramdown
