# Setup
title:        UKChannel8
tagline:      Great TV.<br>By women, for women.<br><i>Register your interest.</i>
baseurl:      ""
paginate:     1

# About/contact
author:
  name:       Kelly-Anne Smith
  url:        http://UKChannel8.com 

# Gems
gems:
  - jekyll-paginate

#Others
markdown: kramdown
